name: 提醒健康打卡
on:
  schedule: 
    - cron: '0 12 * * *'
  workflow_dispatch:
jobs:
  publish:
    name: 提醒健康打卡
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with: 
          python-version: "3.10"
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt
      - name: Run
        env:
          BOT_KEY: ${{ secrets.BOT_KEY_CPU_HEALTH_CODE }}
        run: |
          python ./src/set_mention.py MENTIONED MENTIONED_MOBILE 1 1
          python ./src/main.py text
          python ./src/ROBOT_cpu_health_code.py
          python ./src/main.py markdown
